version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_redsocial
    environment:
      POSTGRES_DB: redsocial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    image: red-social-academica
    container_name: red-social-academica-container
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/redsocial
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8081:8080"
    restart: always
    entrypoint: ["sh", "-c", "sleep 40 && java -jar app.jar"]

volumes:
  db_data:
